version: "3.8"

services:

  accounts:
    image: microservices/accounts-updated:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - microservicebankapp-network

  loans:
    image: microservices/loans-updated:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - microservicebankapp-network

  cards:
    image: microservices/cards-updated:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - microservicebankapp-network

networks:
  microservicebankapp-network:
