version: "3.8"

services:

  configserver:
    image: microservices/configserver-updated:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - microservicebankapp

  eurekaserver:
    image: microservices/eurekaserver-updated:latest
    mem_limit: 700m
    ports:
      - "8070:8070"
    networks:
      - microservicebankapp
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: microservices/accounts-updated:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - microservicebankapp
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/

  loans:
    image: microservices/loans-updated:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - microservicebankapp
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
  cards:
    image: microservices/cards-updated:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - microservicebankapp
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
networks:
  microservicebankapp:
