version: "3.8"

services:

  configserver:
    image: microservices/configserver-updated:latest
    mem_limit: 700m
    ports:
      - "8071:8071"
    networks:
      - microservicebankapp

  accounts:
    image: microservices/accounts-updated:latest
    mem_limit: 700m
    ports:
      - "8080:8080"
    networks:
      - microservicebankapp
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: microservices/loans-updated:latest
    mem_limit: 700m
    ports:
      - "8090:8090"
    networks:
      - microservicebankapp
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: microservices/cards-updated:latest
    mem_limit: 700m
    ports:
      - "9000:9000"
    networks:
      - microservicebankapp
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  microservicebankapp:
